"""auto update

Revision ID: 6e379a2b585b
Revises: 2ec95d57a318
Create Date: 2026-04-24 22:41:53.681276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e379a2b585b'
down_revision: Union[str, Sequence[str], None] = '2ec95d57a318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('api_token_encrypted', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('proxy_group', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.String(), nullable=True),
    sa.Column('test_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_spaces_id'), 'api_spaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_spaces_id'), table_name='api_spaces')
    op.drop_table('api_spaces')
    # ### end Alembic commands ###